# Generated by Django 4.1 on 2022-09-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParraApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('camada', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
