# Generated by Django 4.1 on 2022-09-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParraApp', '0002_curso_delete_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('fechaEntrega', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('apellido', models.CharField(max_length=90)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('apellido', models.CharField(max_length=90)),
                ('correo', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=90)),
            ],
        ),
    ]
