# Generated by Django 4.1 on 2022-09-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParraApp', '0003_entregable_estudiante_profesor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='eurso',
        ),
    ]
