# Generated by Django 4.1 on 2022-09-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParraApp', '0004_rename_curso_eurso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eurso',
            new_name='Curso',
        ),
    ]
